---
# This is a sample database file for the DataMapper ORM
development: &defaults


  #local:
  adapter: sqlserver
  database: i18ntest;
  username: steppescrm
  password: password
  host: seldb


  log_stream: STDOUT  # See: http://blog.aizatto.com/2008/01/17/logging-datamapper-sql-queries-in-merb/
  log_level: 0

test:
  <<:       *defaults

rake:
  <<: *defaults
